### PR TITLE
Skip empty tests

### PR DESCRIPTION
**Pull request by jmartin-sul**
addresses feedback on #85 (https://github.com/LD4P/sinopia_server/pull/85#discussion_r267597278).

slight preference for merging #85 first and then rebasing this and merging it, just to keep the diffs more readable, but happy to do otherwise if people prefer.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@jmartin-sul is this ready for review now?

**Comment by jmartin-sul** [comment]
@mjgiarlo, rebasing, then good to go...

**Comment by mjgiarlo** [comment]
@jmartin-sul 	I think you also need to flip this from pinocchio PR to real-boi PR.

**Comment by mjgiarlo** [comment]
@jmartin-sul cool! will merge as soon as CircleCI goes :green_heart:

**Pull request merged**
